[tool.poetry]
name = "metarix"
version = "0.1.0"
description = ""
authors = ["AtomicNicos <nicolas.boeckh@etu.unige.ch>"]

[tool.poetry.dependencies]
python = "3.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
